import pygame
import sys
"Code Generated by ChatGPT, Edited by Nic Ekstrand"
class Distraction:
    def __init__(self, x, y, size, speed):
        self.x = x
        self.y = y
        self.size = size
        self.speed = speed

    def track(self, target_rect):
        # Move towards the target object
        dx = target_rect.get_x() - self.x
        dy = target_rect.get_y() - self.y
        dist = pygame.math.Vector2(dx, dy).length()

        if dist > 0:
            dx /= dist
            dy /= dist

        self.x += dx * self.speed
        self.y += dy * self.speed

    # Getter methods
    def get_x(self):
        return self.x

    def get_y(self):
        return self.y

    def get_size(self):
        return self.size

    # Setter methods
    def set_x(self, x):
        self.x = x

    def set_y(self, y):
        self.y = y

    def set_size(self, size):
        self.size = size


