"Code Generated by ChatGPT, Edited by Nic Ekstrand"
class Distraction:
    def __init__(self, x, y, size):
        self.x = x
        self.y = y
        self.size = size

    # Getter methods
    def get_x(self):
        return self.x

    def get_y(self):
        return self.y

    def get_size(self):
        return self.size

    # Setter methods
    def set_x(self, x):
        self.x = x

    def set_y(self, y):
        self.y = y

    def set_size(self, size):
        self.size = size


